name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby environment with rbenv
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x # Replace with your desired Ruby version

      - name: Install rbenv
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          exec $SHELL

      - name: Install rbenv-build
        run: |
          mkdir -p "$(rbenv root)"/plugins
          git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

      - name: Install Fastlane
        run: gem install fastlane --user-install

      - name: Build and run Fastlane tests
        run: fastlane tests
