name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane using Bundler
        run: bundle install --path vendor/bundle

      - name: Build and run Fastlane tests
        run: bundle exec fastlane tests
