name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fastlane
        run: gem install fastlane --user-install

      - name: Add gem executable directory to PATH
        run: echo "::add-path::$(ruby -e 'print Gem.user_dir')/bin"

      - name: Build and run Fastlane tests
        run: fastlane tests
