name: build-android-app

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      bundler-path: ${{ steps.set_up_ruby.outputs.bundler-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Bundler
        run: gem install bundler

      - name: Install project dependencies
        run: bundle install

      - name: Export Bundler path
        run: echo "bundler-path=$(bundle which bundler)" >> $GITHUB_ENV

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Ktlint
        run: ./gradlew ktlintCheck

  fastlane:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create dummy google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "1234567890",
              "firebase_url": "https://your-project-id.firebaseio.com",
              "project_id": "your-project-id",
              "storage_bucket": "your-project-id.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:1234567890:android:abcdef",
                  "android_client_info": {
                    "package_name": "com.example.app"
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > app/google-services.json

      - name: Run Fastlane Tests
        run: ${{ env.bundler-path }} exec fastlane test
