name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby environment with rvm
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install rvm
        run: |
          curl -sSL https://get.rvm.io | bash -s stable
          echo 'source "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc
          exec $SHELL

      - name: Install Fastlane
        run: gem install fastlane --user-install -NV

      - name: Build and run Fastlane tests
        run: fastlane tests
