name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby environment with RVM
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x # Replace with your desired Ruby version

      - name: Install Fastlane
        run: gem install fastlane --user-install

      - name: Build and run Fastlane tests
        run: fastlane tests
