name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  fastlane:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Specify the version that matches your project's Gemfile

      - name: Install Bundler
        run: gem install bundler

      - name: Install project dependencies
        run: bundle install

      - name: Run Fastlane
        run: bundle exec fastlane lane_name
