name: build-android-app

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install project dependencies
        run: bundle install

  fastlane:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Run Fastlane test lane
        run: bundle exec fastlane test
